project:
  type: website
  output-dir: docs

website:
  title: "Сергей Мирошниченко"
  navbar:
    left:
      - href: posts.qmd
        text: "Блог"

website-index: blog/

base-url: "/"

format:
  html:
    theme:
      - lux
    css: styles.css