project:
  type: website

website:
  title: "Сергей Мирошниченко"
  navbar:
    left:
      - href: posts.qmd
        text: "Блог"

website-index: blog/

format:
  html:
    theme:
      - lux
    css: styles.css