project:
  type: website
  preview:
    port: 4200
    browser: true

website:
  title: "Сергей Мирошниченко"
  page-navigation: true
  repo-url: https://github.com/s-miroshnichenko/s-miroshnichenko.github.io/
  navbar:
    left:
      - href: posts.qmd
        text: "Блог"

website-index: blog/

format:
  html:
    theme:
      - lux
    css: styles.css